# Generated by Django 4.0.6 on 2022-07-28 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20220722_1934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='recipes',
            new_name='recipe',
        ),
    ]
